### ISSUE TITLE
ScheduledPaymentBatch is not in endpoint nor object

### ISSUE THREAD

**Issue by jleclanche** [bunq/sdk_python#137]
## Steps to reproduce:
I queried some data, going far back enough to hit the issue with my account: `endpoint.Event.list({"count": 50})`

## What should happen:
If I don't go too far back, I get this:
```pytb
>>> endpoint.Event.list({"count": 40})
<bunq.sdk.model.generated.endpoint.BunqResponseEventList object at 0x7ff4d22cb280>
```

## What happens:
```pytb
>>> endpoint.Event.list({"count": 50})
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "(virtualenv)/lib/python3.8/site-packages/bunq/sdk/model/generated/endpoint.py", line 10672, in list
    cls._from_json_list(response_raw, cls._OBJECT_TYPE_GET)
  File "(virtualenv)/lib/python3.8/site-packages/bunq/sdk/model/core/bunq_model.py", line 104, in _from_json_list
    item_deserialized = converter.deserialize(cls, item_unwrapped)
  File "(virtualenv)/lib/python3.8/site-packages/bunq/sdk/json/converter.py", line 444, in deserialize
    return JsonAdapter.deserialize(cls, obj_raw)
  File "(virtualenv)/lib/python3.8/site-packages/bunq/sdk/json/converter.py", line 102, in deserialize
    return cls._deserialize_default(cls_target, obj_raw)
  File "(virtualenv)/lib/python3.8/site-packages/bunq/sdk/json/converter.py", line 117, in _deserialize_default
    return cls._deserialize_dict(cls_target, obj_raw)
  File "(virtualenv)/lib/python3.8/site-packages/bunq/sdk/json/converter.py", line 147, in _deserialize_dict
    dict_deserialized = cls._deserialize_dict_attributes(cls_target, dict_)
  File "(virtualenv)/lib/python3.8/site-packages/bunq/sdk/json/converter.py", line 163, in _deserialize_dict_attributes
    dict_deserialized[value_specs.name] = cls._deserialize_value(value_specs.types, dict_[key])
  File "(virtualenv)/lib/python3.8/site-packages/bunq/sdk/json/converter.py", line 270, in _deserialize_value
    return cls.deserialize(types.main, value)
  File "(virtualenv)/lib/python3.8/site-packages/bunq/sdk/json/converter.py", line 104, in deserialize
    return deserializer.deserialize(cls_target, obj_raw)
  File "(virtualenv)/lib/python3.8/site-packages/bunq/sdk/json/anchor_object_adapter.py", line 33, in deserialize
    object_class = cls._get_object_class(field)
  File "(virtualenv)/lib/python3.8/site-packages/bunq/sdk/json/anchor_object_adapter.py", line 64, in _get_object_class
    raise BunqException(cls.__ERROR_MODEL_NOT_FOUND.format(class_name))
bunq.sdk.exception.bunq_exception.BunqException: ScheduledPaymentBatch is not in endpoint nor object
```

## SDK version and environment
- Tested on [1.13.1](https://github.com/bunq/sdk_python/releases/tag/1.13.1)
- [ ] Sandbox
- [x] Production

**Comment by two-trick-pony-NL** [comment]
👋 Hey @jleclanche 

I work at bunq and am currently reviewing the bunq API docs, open issues and SDK’s and came across your issue. I know it’s been open for a while, and I’d love to understand how it’s impacting you. Beyond the obvious -fixing this issue-, what else could we do to improve your experience with our API?

If you want to share your thoughts on how we can improve on our public API:

📅 I'd love to schedule a 15 minute interview to understand your needs through: [Calendly](https://calendly.com/pvandoorn-bunq/30min)
💬 Or if you don't have time for a call, you can give us some general feedback through this [form](https://bunqsurvey.typeform.com/to/xMu9sEfw)

Your feedback will go straight to our product team! 🚀

**Comment by two-trick-pony-NL** [comment]
Hi! I'm closing this bug as we've completely revamped all our SDKs as part of bunq Update 28.

We took great care to test them thoroughly—and we'll even put them to the test during our hackathon this Friday (feel free to [sign up](https://www.bunq.com/en-nl/hackathon)!).

If this (or a new) issue persists in this new SDK, please reopen the issue so we can jump on it.
